version: "2.2"
services:
  ingress:
    image: istio/proxyv2:1.8.1
    entrypoint: /bin/bash -c 'sleep 1 && /usr/local/bin/envoy -c /etc/envoy/envoy.yaml --bootstrap-version 3 --service-cluster $$(domainname) --service-node $$(hostname) --log-level debug'
    volumes:
      - ${ENVOY_DIR:-./envoy}:/etc/envoy/:z,rw
      - ${WASM_FILTER:-./wasm/threescale_wasm_auth.wasm}:/etc/proxy-wasm/threescale_wasm_auth.wasm:z,rw
    expose:
      - "80"
      - "443"
      - "8080"
      - "8001"
    ports:
      - "80"
      - "443"
      - "8080"
      - "8001"
    scale: 1
    domainname: "ingress"
    networks:
      - ingress
      - mesh
  web:
    image: katacoda/docker-http-server
    expose:
      - "80"
    ports:
      - "80"
    scale: 1
    domainname: "app"
    networks:
      mesh:
        aliases:
          - app
          - web.app

networks:
  ingress:
  mesh:
