version: "2.2"
services:
  ingress:
    image: istio/proxyv2:1.8.2
    entrypoint: /bin/bash -c 'sleep 1 && /usr/local/bin/envoy -c /etc/envoy/envoy.yaml --bootstrap-version 3 --service-cluster $$(domainname) --service-node $$(hostname) --log-level debug'
    volumes:
      - ${ENVOY_DIR:-./envoy}:/etc/envoy/:z,rw
      - ${WASM_FILTER:-./wasm/threescale_wasm_auth.wasm}:/etc/proxy-wasm/threescale_wasm_auth.wasm:z,rw
    expose:
      - "80"
      - "443"
      - "8080"
      - "8001"
    ports:
      - "80"
      - "443"
      - "8080"
      - "8001"
    scale: 1
    domainname: "ingress"
    networks:
      - ingress
      - mesh
  web:
    image: docker.io/kennethreitz/httpbin
    expose:
      - "80"
    ports:
      - "80"
    scale: 1
    domainname: "app"
    networks:
      mesh:
        aliases:
          - app
          - web.app

  keycloak:
    image: quay.io/keycloak/keycloak
    volumes:
      - ${KEYCLOAK_DIR:-./keycloak}:/etc/keycloak/:z,ro
    environment:
      - KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        KEYCLOAK_IMPORT: /etc/keycloak/import.json -Dkeycloak.profile.feature.upload_scripts=enabled
        PROXY_ADDRESS_FORWARDING: true
    expose:
      - "8080"
      - "8443"
    ports:
      - "8080"
      - "8443"
    domainname: "sso"
    networks:
      ingress:
        aliases:
          - sso
          - keycloak.sso
      mesh:

networks:
  ingress:
  mesh:
